import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recipe App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
  types: ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script async src="https://cdn.lordicon.com/lordicon.js"></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
